# The following global variables are algorithm settings. They can be overwritten by
# the node admin by setting the corresponding environment variables.


KAPLAN_MEIER_MINIMUM_ORGANIZATIONS = 3

KAPLAN_MEIER_MINIMUM_NUMBER_OF_RECORDS = 3

KAPLAN_MEIER_ALLOWED_EVENT_TIME_COLUMNS_REGEX = ".*"

# KAPLAN_MEIER_PRIVACY_SNR_EVENT_TIME = -1
# KAPLAN_MEIER_PRIVACY_SNR_EVENT_TIME = 10.0
# KAPLAN_MEIER_PRIVACY_SNR_EVENT_TIME = 5.0
KAPLAN_MEIER_PRIVACY_SNR_EVENT_TIME = 500.0
